CREATE TABLE IF NOT EXISTS `temp_lowaccesscell` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `city` varchar(25) DEFAULT NULL,
    `subNetwork` varchar(25) DEFAULT NULL,
    `cell` varchar(25) DEFAULT NULL,
    `hour_id` varchar(25) DEFAULT NULL,
    `前天小时数` varchar(25) DEFAULT NULL,
    `昨天小时数` varchar(25) DEFAULT NULL,
    `今天小时数` varchar(25) DEFAULT NULL,
    `RRC建立失败次数(最新)` decimal(18,0) DEFAULT NULL,
    `ERAB建立失败次数(最新)` decimal(18,0) DEFAULT NULL,
    `RRC建立失败次数(总)` decimal(18,0) DEFAULT NULL,
    `ERAB建立失败次数(总)` decimal(18,0) DEFAULT NULL,
    `RRC建立失败次数(今日)` decimal(18,0) DEFAULT NULL,
    `ERAB建立失败次数(今日)` decimal(18,0) DEFAULT NULL,
    `严重程度` decimal(18,2) DEFAULT NULL,
    `告警数量` decimal(18,0) DEFAULT NULL,
    `平均PRB` varchar(25) DEFAULT NULL,
    `RSRP<-116的比例` decimal(18,2) DEFAULT NULL,
    `最高RRC用户数` decimal(18,0) DEFAULT NULL,
    `重叠覆盖度` varchar(255) DEFAULT NULL,
    `需要加邻区数量` varchar(255) DEFAULT NULL,
    `RSRQ<-15.5的比例` decimal(18,2) DEFAULT NULL,
    `参数` decimal(18,2) DEFAULT NULL,
    `Polar-告警` decimal(18,2) DEFAULT NULL,
    `Polar-弱覆盖` decimal(18,2) DEFAULT NULL,
    `Polar-重叠覆盖` varchar(255) DEFAULT NULL,
    `Polar-质差` decimal(18,2) DEFAULT NULL,
    `Polar-邻区` varchar(255) DEFAULT NULL,
    `Polar-最高RRC用户数` decimal(18,0) DEFAULT NULL,
    `Polar-干扰` decimal(18,2) DEFAULT NULL,
    `Polar-参数` decimal(18,2) DEFAULT NULL,
    `无线接通率_干扰` decimal(18,2) DEFAULT NULL,
    `无线接通率_质差` decimal(18,2) DEFAULT NULL,
    `无线接通率_RRC建立成功率` decimal(18,2) DEFAULT NULL,
    `无线接通率_ERAB建立成功率` decimal(18,2) DEFAULT NULL,
    `无线接通率_弱覆盖` decimal(18,2) DEFAULT NULL,
    `MAC层时延` decimal(18,2) DEFAULT NULL,
    `SRcongestion数` decimal(18,0) DEFAULT NULL,
    `SR拥塞比` decimal(18,2) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `hour_index` (`hour_id`),
    KEY `city_index` (`city`),
    KEY `subNet_index` (`subNetwork`),
    KEY `cell_index` (`cell`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;