CREATE TABLE IF NOT EXISTS `temp_badhandovercell` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `city` varchar(25) DEFAULT NULL,
              `subNetwork` varchar(25) DEFAULT NULL,
              `cell` varchar(25) DEFAULT NULL,
              `hour_id` varchar(25) DEFAULT NULL,
              `前天小时数` varchar(25) DEFAULT NULL,
              `昨天小时数` varchar(25) DEFAULT NULL,
              `今天小时数` varchar(25) DEFAULT NULL,
              `准备切换失败数(最新)` decimal(18,0) DEFAULT NULL,
              `执行切换失败数(最新)` decimal(18,0) DEFAULT NULL,
              `准备切换失败数(总)` decimal(18,0) DEFAULT NULL,
              `执行切换失败数(总)` decimal(18,0) DEFAULT NULL,
              `准备切换失败数(今日)` decimal(18,0) DEFAULT NULL,
              `执行切换失败数(今日)` decimal(18,0) DEFAULT NULL,
              `严重程度` decimal(18,2) DEFAULT NULL,
              `告警数量` decimal(18,0) DEFAULT NULL,
              `平均PRB` varchar(25) DEFAULT NULL,
              `RSRP<-116的比例` decimal(18,2) DEFAULT NULL,
              `关联度` decimal(18,2) DEFAULT NULL,
              `重叠覆盖度` decimal(18,2) DEFAULT NULL,
              `需要加邻区数量` decimal(18,2) DEFAULT NULL,
              `RSRQ<-15.5的比例` decimal(18,2) DEFAULT NULL,
              `参数` decimal(18,2) DEFAULT NULL,
              `Polar-告警` decimal(18,2) DEFAULT NULL,
              `Polar-弱覆盖` decimal(18,2) DEFAULT NULL,
              `Polar-重叠覆盖` decimal(18,2) DEFAULT NULL,
              `Polar-质差` decimal(18,2) DEFAULT NULL,
              `Polar-邻区` decimal(18,2) DEFAULT NULL,
              `Polar-高话务` decimal(18,2) DEFAULT NULL,
              `Polar-干扰` decimal(18,2) DEFAULT NULL,
              `Polar-参数` decimal(18,2) DEFAULT NULL,
              `切换成功率_准备切换成功率` decimal(18,2) DEFAULT NULL,
              `切换成功率_执行切换成功率` decimal(18,2) DEFAULT NULL,
              `切换成功率_干扰` decimal(18,2) DEFAULT NULL,
              `切换成功率_质差` decimal(18,2) DEFAULT NULL,
              `切换成功率_弱覆盖` decimal(18,2) DEFAULT NULL,
              PRIMARY KEY (`id`),
              KEY `hour_index` (`hour_id`),
              KEY `city_index` (`city`),
              KEY `subNet_index` (`subNetwork`),
              KEY `cell_index` (`cell`)
            ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;